# Generated by Django 4.2.2 on 2023-06-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('img', models.ImageField(upload_to='static/Fotos/')),
            ],
        ),
    ]
